services:
  frontend:
    container_name: logpunch_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_APP_ENV=docker
    networks:
      - logpunch_network

networks:
  logpunch_network:
    external: true
