services:
  server:
    image: logpunch-backend
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: ["dotnet", "run", "--urls", "http://*:7206"]
    ports:
      - "7206:7206"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7206
      - JWT_KEY=8e73b388-707e-49cf-912d-334c988af3e0
      - JWT_ISSUER=logpunch
      - JWT_AUDIENCE=Audience
      - ConnectionStrings__LogpunchDb=Host=database;Database=logpunchdb;Username=logpunchuser;Password=logpunch1234
    networks:
      - logpunch_network
    volumes:
      - ./src/Server/appsettings.json:/app/appsettings.json
      - ./src/Server/appsettings.Development.json:/app/appsettings.Development.json

networks:
  logpunch_network:
    external: true
