apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: pl-prod
spec:
  selector:
    matchLabels:
      app: punchlog-frontend
  template:
    metadata:
      labels:
        app: punchlog-frontend
    spec:
      containers:
        - name: frontend-deployment
          image: 767397975346.dkr.ecr.eu-north-1.amazonaws.com/punchlog-fe:${fe_image_tag}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 256Mi
              cpu: "500m"
