apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: pl-prod
spec:
  selector:
    app: punchlog-frontend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
